name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # deploy only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t demo-project .

      - name: Save Docker Image as Tarball
        run: docker save demo-project | gzip > demo-project.tar.gz

      - name: Copy Image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "demo-project.tar.gz"
          target: "~/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker load < demo-project.tar.gz
            docker stop next-app || true
            docker rm next-app || true
            docker run -d -p 80:5000 --name next-app demo-project
